### ISSUE TITLE
./.utils/check-proxy.sh connect: Connection refused

### ISSUE THREAD

**Issue by stefthoen** [schliflo/bedrock-docker#10]
I tried to get this working, but when I do `make up` I get the error message that's in  the title. It fails on line 4 and 7. When I go to the URL that's been generated, I get a Dinghy page.

I'm on Ubuntu and this is the first time I'm trying out Docker. I don't really get the following line in the README: `Configure your system to resolve .docker domains to 127.0.0.1`. I added the projectname.docker URL to `/etc/hosts`. Did I interpret the instruction correctly?

It also says that the `PROJECT_NAME` variable hasn't been set, even though I did set it in the `Makefile`.

**Comment by schliflo** [comment]
If your local .docker domain shows the dinghy page the resolving part should not be the issue (via hosts is fine - you could do this via a custom resolver as well).
Can you post the result of `docker ps` - this should show which containers are running and what ports they are mapped to.

**Comment by stefthoen** [comment]
This is my output. Thanks by the way. Really appreciate your help.
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                                                           NAMES
a858bab35307        qdn-docker-bedrock_app          "/entrypoint supervi…"   3 minutes ago       Up 3 minutes        9000/tcp                                                                        qdn-docker-bedrock_app_1
1305daaa1a7f        phpmyadmin/phpmyadmin           "/run.sh supervisord…"   3 minutes ago       Up 3 minutes        80/tcp, 9000/tcp                                                                qdn-docker-bedrock_phpmyadmin_1
7f4767dede5e        mariadb                         "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes        3306/tcp                                                                        qdn-docker-bedrock_db_1
883877f7ff61        mailhog/mailhog                 "MailHog"                3 minutes ago       Up 3 minutes        1025/tcp, 8025/tcp                                                              qdn-docker-bedrock_mail_1
0b237465349e        codekitchen/dinghy-http-proxy   "/app/docker-entrypo…"   3 minutes ago       Up 3 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 19322/tcp, 0.0.0.0:19322->19322/udp   bedrock-docker-http-proxy
```

**Comment by schliflo** [comment]
This seems fine. Some more questions then:
What's the value you entered for `PROJECT_NAME` in the makefile? 
Whats the output of `make urls`?
Do you have errors in the output of `make logs`?

No problem by the way - I'm glad you use my tool and might find it useful :)

**Comment by stefthoen** [comment]
To make it extra confusing I'm on another computer right now. The WP site is working, so that's good news! But Mailhog and PHPMyAdmin seem to be broken. I was also using a `qdn` table prefix. When I try to import the database from staging I get an error message that my database is using the `wp` table prefix. This is my `docker ps` output by the way. My `PROJECT_NAME` is `qdn`.
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                                                           NAMES
34201bbf0e29        qdn_web                         "/bin/sh -c 'envsubs…"   9 minutes ago       Up 9 minutes        80/tcp                                                                          qdn_web_1_bf306c043a37
d2d51ee8eda2        qdn_app                         "/entrypoint supervi…"   9 minutes ago       Up 9 minutes        9000/tcp                                                                        qdn_app_1_6694fe430787
6d925139ffe1        phpmyadmin/phpmyadmin           "/run.sh supervisord…"   9 minutes ago       Up 9 minutes        80/tcp, 9000/tcp                                                                qdn_phpmyadmin_1_a5c3ef6e249f
d8beb10427c5        mailhog/mailhog                 "MailHog"                9 minutes ago       Up 9 minutes        1025/tcp, 8025/tcp                                                              qdn_mail_1_def9abefb819
906d7fc1a133        mariadb                         "docker-entrypoint.s…"   9 minutes ago       Up 9 minutes        3306/tcp                                                                        qdn_db_1_ee18b79d6c3c
12343b83a17c        codekitchen/dinghy-http-proxy   "/app/docker-entrypo…"   9 minutes ago       Up 9 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 19322/tcp, 0.0.0.0:19322->19322/udp   bedrock-docker-http-proxy
```

The output of `make urls` is:
```
[0;37m-------------------------------------------------------------------[0m
[0;32m You can access your project at the following URLS:[0m
[0;37m-------------------------------------------------------------------[0m

[0;36mBackend:     http://qdn.docker/wp/wp-admin/[0m
[0;36mFrontend:    http://qdn.docker/[0m
[0;36mMailhog:     http://mail.qdn.docker/[0m
[0;36mPHPMyAdmin:  http://phpmyadmin.qdn.docker/[0m
```
The only real error  message that I see in `make logs` is this one:
```
test_1_b98addb736f5 | 2018/11/09 19:53:48 [emerg] 1#1: open() "/etc/nginx/site.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:160
test_1_b98addb736f5 | nginx: [emerg] open() "/etc/nginx/site.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:160
qdn_test_1_b98addb736f5 exited with code 1
d
```

**Comment by schliflo** [comment]
I just tested myself with a fresh project and it seems to be working fine here. Maybe mapping `mail.qdn.docker` and `phpmyadmin.qdn.docker` to 127.0.0.1 via /etc/hosts will solve this issue.
Using a table prefix different from `wp_` is currently not supported. However you can change this easily at: https://github.com/schliflo/bedrock-docker/blob/master/docker-compose.yml#L22
I'll open an issue to make sure this is supported in the future.

**Comment by stefthoen** [comment]
You were right. I had to map mail and phpmyadmin as well. And thank you for pointing me to the right place to change the table prefix. You made something really cool and I'm going to use it a lot. :+1: 

I do still get those `./utils/check-proxy.sh` errors, but everything seems to be working just fine. I hope I can get it to work on my work PC as well next monday. 

Do you know if there is a way to keep your database data when you stop and remove the database container?

**Comment by schliflo** [comment]
I'm glad it works now!
Ignore these `./utils/check-proxy.sh` errors for now, maybe i need another way to check wether ports are occupied or not.

You can use `make mysql-backup` and `make mysql-restore` as described here: https://github.com/schliflo/bedrock-docker#backup-a-database

I'm closing this for now - feel free to create a new one if you encounter any more issues :)
