### ISSUE TITLE
Configuration for multisite

### ISSUE THREAD

**Issue by elvishp2006** [schliflo/bedrock-docker#14]
There is a way to get this working on multisite subdomain and subdirectory?

**Comment by schliflo** [comment]
You can add multiple domains here https://github.com/schliflo/bedrock-docker/blob/master/docker-compose.yml#L40
for example like this:
```
- VIRTUAL_HOST=$PROJECT_NAME.docker,subdomain1.$PROJECT_NAME.docker,subdomain2.$PROJECT_NAME.docker
```
As far as I know bedrock + multisite + nginx requires some fancy configuration. You can edit the nginx.conf here: https://github.com/schliflo/bedrock-docker/blob/master/.docker/web/etc/nginx/site.conf.template (you probably need to hardcode the server_name when using multiple hosts)

So in theory you can get this working - the difficulty is configuring bedrock & nginx accordingly.
I do however not plan to support this special case by default with bedrock-docker. Feel free to send a PR though :)

**Comment by schliflo** [comment]
Closing this for now. If you find a problem specific to bedrock-docker feel free to report here - I'll reopen the issue.
