### ISSUE TITLE
ERROR: unsatisfiable constraints:

### ISSUE THREAD

**Issue by dnspnjrs** [schliflo/bedrock-docker#2]
Would be great if this would work.

Unfortunately it does not, 

Followed the instructions but receiving this error after step:
`Step 2/9 : RUN apk add --no-cache musl-dev go`

Error:
```
ERROR: unsatisfiable constraints:
  musl-dev (missing):
    required by: world[musl-dev]
  binutils (missing):
    required by: go-1.8.4-r0[binutils]
                 go-1.8.4-r0[binutils]
  gcc (missing):
    required by: go-1.8.4-r0[gcc]
                 go-1.8.4-r0[gcc]
ERROR: Service 'app' failed to build: The command '/bin/sh -c apk add --no-cache musl-dev go' returned a non-zero code: 4
make: *** [update] Error 1
```

**Comment by schliflo** [comment]
Thank you for reporting the issue. Which environment are you running this in (OS, Dinghy, Docker versions)?
I could not reproduce the issue with the following setup/versions:
macOS 10.12.6 (16G1114) Sierra
Docker version 17.12.0-ce, build c97c6d6
Dinghy 4.6.1

Even if running `docker run --rm -ti webdevops/php:alpine-php7 bash` and then doing the build step manually with `apk add --no-cache musl-dev go` does work for me.

**Comment by dnspnjrs** [comment]
Thanks for your response! I this problem is resolved and it was due to the image being unavailable.

I am now able to install it correctly however I cant get dinghy running that its points to the correct host. It keeps presenting the default dhingy page. 

Maybe in the how-to it would be helpful to describe how to use dinghy correctly.

Thanks in advance.

**Comment by schliflo** [comment]
Ok, good to hear.

What does `dinghy status` say for you? Should look like this:
```
   VM: running
  NFS: running
 FSEV: running
  DNS: running
PROXY: running

Your environment variables are already set correctly.
```

**Comment by dnspnjrs** [comment]
All look running.

```
   VM: running
  NFS: running
 FSEV: running
  DNS: running
PROXY: running
```

Also get this after installing dinghy
```

    export DOCKER_HOST=tcp://192.168.99.100:2376
    export DOCKER_CERT_PATH=/Users/name/.docker/machine/machines/dinghy
    export DOCKER_TLS_VERIFY=1
    export DOCKER_MACHINE_NAME=dinghy

```

**Comment by schliflo** [comment]
If Dinghy doesn't report that your environment variables are set correctly (like in my example above) you need to export them.

**Comment by dnspnjrs** [comment]
Should have clarified, it does also say:

` Your environment variables are already set correctly.`

Did you set anything specific in dighy while making this setup?

**Comment by schliflo** [comment]
Then dinghy should be running fine. 
I have no special configuration - this should work out of the box.
Can you check if the contents of this file are correct: `/etc/resolver/docker` - should point to your dinghy vm as nameserver -> IP `192.168.99.100` with port `2376` in your case.

**Comment by dnspnjrs** [comment]
This seems to have resolved it!

I changed the port manually to `2376`, for some reason dinghy didn't change this port with the install?

**Comment by schliflo** [comment]
Happy to hear that! :)
