### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by xf-** [schliflo/bedrock-docker#21]
Support SSL (self-singed or something like minica) and the advantages like http2 http push and other features. Also gets rid of annoying "Warning: You will send your password in a not secure form" messages.

> If you want a little more realism in your development certificates, you can use minica to generate your own local root certificate, and issue end-entity (aka leaf) certificates signed by it. You would then import the root certificate rather than a self-signed end-entity certificate.
https://letsencrypt.org/docs/certificates-for-localhost/

nginx proxy supports - CERT_NAME=

mkcert works better, because you can set the output filename and the root can be installed in firefox and chrome (and some systems).

**Comment by schliflo** [comment]
I'd be open to a PR as long as it's optional and is disabled by default. Basically just to keep this as simple to use as possible - but other than that I think this would be a great addition :)

**Comment by schliflo** [comment]
[docker-mate](https://docker-mate.dev/) is released as a successor and supports this feature :)
