### ISSUE TITLE
Fully functional replacement for Trellis+Bedrock?

### ISSUE THREAD

**Issue by BobbyBabes** [schliflo/bedrock-docker#22]
I was just checking out your code and have questions.

Questions:

1) I noticed that Alpine Linux with NGINX is the basis. But is this a fully functional replacement for Trellis+Bedrock with everything included that Trellis and Bedrock have?
2) Has this also been tested with Sage?
3) Do you have a link to the Docker Hub page of ```FROM amd64/nginx:alpine```?
(Source – https://github.com/schliflo/bedrock-docker/blob/master/.docker/web/Dockerfile#L1)

**Comment by xf-** [comment]
1. No, Trellis is a deployment tool (Based on headers on website). I think @schliflo and other use some kind of build chain to deploy. This is for development.
2. Sage is only a theme in Bedrock or? If nginx conf is the same it should work.
3. https://hub.docker.com/_/nginx - click on architecture amd64

**Comment by BobbyBabes** [comment]
> Ansible playbooks for setting up a LEMP stack for WordPress.
Source – https://github.com/roots/trellis

> Ansible playbooks for setting up a LEMP stack for WordPress.
>
>    Local development environment with Vagrant
Source – https://github.com/roots/trellis

> Ansible playbooks for a WordPress LEMP stack https://roots.io/trellis/
Source – https://github.com/roots/trellis

> WordPress development and production servers done right
Source – https://roots.io/trellis/

> Vagrant virtual machine for development
Source – https://roots.io/trellis/

**Comment by schliflo** [comment]
Just for clarification: this is _not_ a Trellis replacement. It only provides a lightweight, Docker-based development environment. This project is not suitable for production use or anything like that. In fact I'd explicitly advise against running your database in a container.
Thanks @xf- for answering and thank you @BobbyBabes for asking. Feel free to ask again if you need more info.
