### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by BobbyBabes** [schliflo/bedrock-docker#23]
I was just checking out your code and noticed what looks like a typo.

You're checking twice for lower case ```"y"``` input:
```Bash
if [ "$backupOK" = "Yes" ] || [ "$backupOK" = "yes" ] || [ "$backupOK" = "y" ] || [ "$backupOK" = "y" ]; then
```
Source — https://github.com/schliflo/bedrock-docker/blob/master/.utils/mysql-backup.sh#L11     

Maybe convert to uppercase or lowercase first, like so:
```Bash
backupOK=`echo "$backupOK" | /usr/bin/tr '[:lower:]' '[:upper:]'`
if [ "$backupOK" == "Y" ] || [ "$backupOK" == "YES" ]; then
```
```Bash
backupOK=`echo "$backupOK" | /usr/bin/tr '[:upper:]' '[:lower:]'`
if [ "$backupOK" == "y" ] || [ "$backupOK" == "yes" ]; then
```

**Comment by xf-** [comment]
Normal sting operator in bash can do that 

e.g. starts with in regex and no extra utility
```bash
if [[ ${backupOK} =~ ^[Yy] ]] ; then
```

or 

```bash
if [[ ${backupOK,,} == "yes" ]] || [[ ${backupOK,,} == "y" ]] ; then
```

**Comment by BobbyBabes** [comment]
Yeah, it's always easy to improve on a working example. Unless of course it's with an improvement which sacrifices readability. Focusing on the typo is apparently less important.
Also, I started my sentence with "Maybe", which leaves it open to whatever the repo owner, who I was addressing, wants to resolve it. My code was posted to demonstrate a simplification of the check by converting to uppercase or lowercase first. Not to start a contest of who has the bigger coding dick.

**Comment by xf-** [comment]
@BobbyBabes we work some major changes (i use the repo not only for wordpress). You can select the cms/custom/... you want. This line is already changed to my first example before you opened the issue. Is planed to be released someday, but we need a concept and fix some issues regarding OSX.

**Comment by schliflo** [comment]
I'll leave this open as this is a valid issue. Thank's @BobbyBabes for bringing this to our attention. 
@xf- and me are working on a re-structured and more generalised (suitable for multiple platforms, not only Bedrock/Wordpress) release. We'll address this issue there. If you need a fix right now, feel free to open a PR (doesn't have to be the shortest code possible...)
