### ISSUE TITLE
Tester(s) wanted

### ISSUE THREAD

**Issue by xf-** [schliflo/bedrock-docker#24]
Like @schliflo wrote in [other issue](https://github.com/schliflo/bedrock-docker/issues/23#issuecomment-492120473), we work on restructuring the project and add some features and allow a lot of optional/project specific options. We plan to release it after all our ideas are included and it works on Linux and OSX (bash scripts differ in syntax). We already use it in our daily work & projects.

**To release a better working software some tests and feedback would be great.**
-> Write a comment if you interested. A little bit of knowledge about development/docker would be great.

Will be some Wordpress Bedrock functionality removed?
**NO**, optional/dynamic configs allow to add even more CMS & project specific commands and tools and also allows to extend them without touching the released files.

Changelist (so far):
- Optional containers
  - CI, Composer
  - (Optional) per system/cms
  - (Optional) per project in project git - add NodeJs Container or a Elastic for development
- Makefile like containers 
   - (Optional) per system/cms - make wp for cli
  - (Optional) per project in project git - scss/less compieler
- Default bash and fallback sh for make ssh
- env file for nearly everything
- Change php version or php vs php-dev container
- Hooks to load projects with specific settings
- SSL (currently required) uses mkcert to generate a root and included in wanted browsers. afterwards it generates certs
- Git script after install (add git y/n push it remote (optional as well))
....

**Comment by xf-** [comment]
We (schliflo and me) are near the finish line.

Bedrock Wordpress and other systems are supported. We used it the last year and you can throw nearly everything php related into setup and it will run (nginx config required).
Currently we are on finishing stage of a small documentation. A lot of features got added to adjust settings for every project and still be able to update docker with a simple git pull.

**Comment by schliflo** [comment]
[docker-mate](https://docker-mate.dev/) is released now :)
