### ISSUE TITLE
Issues with Proxy

### ISSUE THREAD

**Issue by bradymwilliams** [schliflo/bedrock-docker#26]
> For native docker installs you need to configure your system to resolve .docker domains to 127.0.0.1
Can you point me to a guide for this.

Dinghy has issues with latest few OSX versions and xhyve

**Comment by schliflo** [comment]
This project is no longer maintained as we developed https://github.com/docker-mate/docker-mate as a successor, which supports more sytems, local SSL and is overall more extensible and improved. I'd highly suggest having a look at [docker-mate](https://docker-mate.dev/).
That being said, things should still work fine here. 

You just need to start the dinghy proxy (no need to use the whole dinghy VM):
```bash
docker run -d --restart=always \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    -v ~/.dinghy/certs:/etc/nginx/certs \
    -p 80:80 -p 443:443 \
    -p 19322:19322/udp \
    -e DNS_IP=127.0.0.1 \
    -e CONTAINER_NAME=docker-mate-http-proxy \
    --name docker-mate-http-proxy \
    codekitchen/dinghy-http-proxy
```

and create a local resolver for the `.docker` domains. This is easy on macOS -> just create the following file:
`/etc/resolver/docker`
```
port 19322
nameserver 127.0.0.1
```

After restarting your system, resolving `.docker` domains schould work as expected.

**Comment by bradymwilliams** [comment]
THANKS

**Comment by xf-** [comment]
@bradymwilliams i tried yesterday to run pi-hole as DNS server for my network and add the wildcard to avoid local changes. It works without any issue. Pi-hole also uses dnsmasq, supports local DNS in Web UI, but wildcard needs to be in config from pi-hole dnsmasq.
Allows also to access projects in local network and test on mobile devices for example.
